// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5gBvA20CHAJNeHhZPKNppcjOxgcSdDNw',
    appId: '1:81978853142:web:97b3cf5aeede3a4fd17237',
    messagingSenderId: '81978853142',
    projectId: 'flutter-auth-2762a',
    authDomain: 'flutter-auth-2762a.firebaseapp.com',
    storageBucket: 'flutter-auth-2762a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANDI4zpZb6xq6SyOCND_EQ7p2GNmO08GY',
    appId: '1:81978853142:android:1288c074edb0c1f9d17237',
    messagingSenderId: '81978853142',
    projectId: 'flutter-auth-2762a',
    storageBucket: 'flutter-auth-2762a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd0GRorBjdNVxyWREOXlSLxogszNg1XYI',
    appId: '1:81978853142:ios:921f1d10553f5241d17237',
    messagingSenderId: '81978853142',
    projectId: 'flutter-auth-2762a',
    storageBucket: 'flutter-auth-2762a.appspot.com',
    iosClientId: '81978853142-efd0cf8kg0tjmnj0vj1nqlnkjcq2lrso.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd0GRorBjdNVxyWREOXlSLxogszNg1XYI',
    appId: '1:81978853142:ios:921f1d10553f5241d17237',
    messagingSenderId: '81978853142',
    projectId: 'flutter-auth-2762a',
    storageBucket: 'flutter-auth-2762a.appspot.com',
    iosClientId: '81978853142-efd0cf8kg0tjmnj0vj1nqlnkjcq2lrso.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );
}
